# Generated by Django 3.1.5 on 2021-01-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='short_description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Short Description'),
        ),
    ]
